events {
    worker_connections 1024;
}

http {
    upstream recipe_stats {
        server recipe-stats-service:5001;
    }

    upstream weather_service {
        server weather-service:5002;
    }

    server {
        listen 80;

        location /stats/ {
            proxy_pass http://recipe_stats/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /weather/ {
            proxy_pass http://weather_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://recipe_stats/health;
        }
    }
}